import type { Insulation, RoomType, SunExposure, WindowRatio } from "./types";

export const hvacConfig = {
  heatLoad: {
    btuPerSqm: 550,
    safetyBuffer: 1.15,
    btuPerHp: 9000,
    btuPerTon: 12000,
    defaults: {
      ceilingHeightM: 2.7,
      occupancy: 1,
      sunExposure: "low" as SunExposure,
      windowRatio: "medium" as WindowRatio,
      roomType: "bedroom" as RoomType,
      insulation: "average" as Insulation,
    },
    validation: {
      minAreaSqm: 5,
      maxAreaSqm: 5000,
      minCeilingHeightM: 2,
      maxCeilingHeightM: 12,
      minOccupancy: 1,
      maxOccupancy: 2000,
      bedroomHighAreaSqm: 60,
      denseOccupancyPerSqm: 0.35,
    },
  },
  environmentalWeights: {
    ceilingPoints: [
      [2.4, 0.95],
      [2.7, 1],
      [3, 1.08],
      [3.5, 1.2],
      [4, 1.35],
      [5, 1.55],
      [6, 1.75],
      [8, 2],
    ],
    insulation: {
      poor: 1.25,
      average: 1,
      good: 0.85,
    } satisfies Record<Insulation, number>,
    windowRatio: {
      low: 0.95,
      medium: 1.1,
      high: 1.3,
    } satisfies Record<WindowRatio, number>,
  },
  solarAdjustments: {
    none: { multiplier: 0.9, explanation: "shaded exposure reduces peak solar gain" },
    low: { multiplier: 1, explanation: "low direct sun adds little solar gain" },
    medium: { multiplier: 1.15, explanation: "moderate afternoon solar exposure increases cooling demand by about 15%" },
    high: { multiplier: 1.3, explanation: "strong direct sun increases cooling demand by about 30%" },
    very_high: { multiplier: 1.45, explanation: "very strong sun or roof exposure increases cooling demand by about 45%" },
  } satisfies Record<SunExposure, { multiplier: number; explanation: string }>,
  roomProfiles: {
    bedroom: { multiplier: 0.8, occupancyBtu: 400, priorities: ["quiet", "comfort"] },
    living_room: { multiplier: 0.9, occupancyBtu: 450, priorities: ["comfort", "balanced"] },
    office: { multiplier: 1, occupancyBtu: 600, priorities: ["efficiency", "quiet"] },
    commercial_hall: { multiplier: 1.15, occupancyBtu: 700, priorities: ["air_distribution", "capacity"] },
    restaurant: { multiplier: 1.35, occupancyBtu: 900, priorities: ["capacity", "ventilation"] },
    server_room: { multiplier: 1.6, occupancyBtu: 300, priorities: ["reliability", "efficiency"] },
    gym: { multiplier: 1.4, occupancyBtu: 1000, priorities: ["capacity", "air_distribution"] },
    classroom: { multiplier: 1.1, occupancyBtu: 650, priorities: ["quiet", "ventilation"] },
    retail_store: { multiplier: 1.2, occupancyBtu: 700, priorities: ["air_distribution", "comfort"] },
  } satisfies Record<RoomType, { multiplier: number; occupancyBtu: number; priorities: string[] }>,
  applianceHeatBtu: {
    tv: 400,
    computer: 600,
    refrigerator: 1200,
    microwave: 1500,
    lightingWattsMultiplier: 3.41,
    otherWattsMultiplier: 3.41,
  },
  btuRanges: [
    { min: 0, max: 8000, hpOptions: [0.75, 1] },
    { min: 7000, max: 11000, hpOptions: [0.75, 1, 1.5] },
    { min: 10000, max: 16000, hpOptions: [1, 1.5, 2] },
    { min: 15000, max: 23000, hpOptions: [1.5, 2, 2.5] },
    { min: 22000, max: 32000, hpOptions: [2.5, 3, 3.5] },
    { min: 30000, max: 45000, hpOptions: [3, 4, 5] },
  ],
  systemCatalog: [
    {
      id: "window_type",
      label: "Window Type",
      hpCatalog: [0.75, 1, 1.5, 2],
      compatibleBtuMin: 4500,
      compatibleBtuMax: 18000,
      maxAreaSqm: 35,
      upfrontCost: 5,
      quietness: 2,
      efficiency: 2,
      comfort: 2,
      installSimplicity: 5,
      estimatedWattsPerBtu: 0.105,
      cooldownFactor: 1.08,
      explanation: "lowest upfront cost when a window opening or wall sleeve is available",
    },
    {
      id: "standard_split",
      label: "Standard Split Type",
      hpCatalog: [1, 1.5, 2, 2.5, 3],
      compatibleBtuMin: 7000,
      compatibleBtuMax: 30000,
      maxAreaSqm: 80,
      upfrontCost: 3,
      quietness: 4,
      efficiency: 3,
      comfort: 4,
      installSimplicity: 3,
      estimatedWattsPerBtu: 0.095,
      cooldownFactor: 0.98,
      explanation: "good balance of comfort, indoor noise, and residential availability",
    },
    {
      id: "split_inverter",
      label: "Split Inverter",
      hpCatalog: [1, 1.5, 2, 2.5, 3, 4],
      compatibleBtuMin: 7000,
      compatibleBtuMax: 36000,
      maxAreaSqm: 100,
      upfrontCost: 2,
      quietness: 5,
      efficiency: 5,
      comfort: 5,
      installSimplicity: 3,
      estimatedWattsPerBtu: 0.075,
      cooldownFactor: 0.92,
      explanation: "quietest and most efficient option for rooms used many hours per day",
    },
    {
      id: "ceiling_cassette",
      label: "Ceiling Cassette",
      hpCatalog: [2, 2.5, 3, 5],
      compatibleBtuMin: 18000,
      compatibleBtuMax: 48000,
      minAreaSqm: 25,
      upfrontCost: 2,
      quietness: 4,
      efficiency: 4,
      comfort: 4,
      installSimplicity: 2,
      estimatedWattsPerBtu: 0.088,
      cooldownFactor: 0.95,
      explanation: "better airflow distribution for open offices, retail, and rooms with ceiling space",
    },
    {
      id: "multi_split",
      label: "Multi-Split Inverter",
      hpCatalog: [2, 2.5, 3, 4, 5],
      compatibleBtuMin: 18000,
      compatibleBtuMax: 45000,
      minAreaSqm: 30,
      upfrontCost: 1,
      quietness: 5,
      efficiency: 5,
      comfort: 5,
      installSimplicity: 2,
      estimatedWattsPerBtu: 0.078,
      cooldownFactor: 0.94,
      explanation: "best when several connected zones share one outdoor unit",
    },
    {
      id: "packaged_unit",
      label: "Packaged / Ducted Unit",
      hpCatalog: [5, 7.5, 10, 12.5, 15],
      compatibleBtuMin: 42000,
      compatibleBtuMax: 140000,
      minAreaSqm: 70,
      upfrontCost: 1,
      quietness: 3,
      efficiency: 4,
      comfort: 4,
      installSimplicity: 1,
      estimatedWattsPerBtu: 0.085,
      cooldownFactor: 0.96,
      explanation: "appropriate for larger open spaces where several room ACs would perform poorly",
    },
  ],
  recommendationWeights: {
    baseCompatibility: 30,
    sizingFit: 15,
    roomProfile: 12,
    preferences: 18,
    constraints: 20,
    budget: {
      lowest_upfront: { upfrontCost: 10, efficiency: 1, quietness: 1 },
      balanced: { upfrontCost: 3, efficiency: 5, quietness: 4 },
      premium_comfort: { upfrontCost: 1, efficiency: 8, quietness: 8 },
    },
    noise: {
      standard: 0,
      quiet: 10,
    },
    energy: {
      standard: 0,
      important: 10,
    },
  },
} as const;
